version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  app:
    build: .
    image: my-node-app
    volumes:
      - $PWD:/usr/src/app
    ports:
      - 13000:3000
